### ISSUE TITLE
Create a stream from Tasks

### ISSUE THREAD

**Issue by dmzkrsk** [vxgmichel/aiostream#1]
Is it possible to create a stream from existing tasks?

I.e. a have a bunch of requests from `aiohttp` wrapped in `Task`s and want to iterate them in order of complete?

**Comment by dmzkrsk** [comment]
Ended up using something like this.

```python
@aiostream.operator
async def iterator_from_awaitable(coro):
    task = asyncio.ensure_future(coro)
    await task

    yield task.result()

@aiostream.operator
def stream_from_coroutines(*coroutines):
    iterators = [iterator_from_awaitable.raw(c) for c in coroutines]
    return aiostream.stream.merge.raw(*iterators)
```

Should I create a PR? Is it worth adding to the library?

**Comment by vxgmichel** [comment]
Interesting! The tricky part here is the naming... Maybe `stream.as_completed`, since it is similar to [asyncio.as_completed](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed)? Then what about the first one, `stream.result`?

**Comment by vxgmichel** [comment]
Since [v0.3.0](https://github.com/vxgmichel/aiostream/releases/tag/v0.3.0), it's possible to implement `as_completed` using `map`:

```python
from aiostream import stream, operator

@operator
async def as_completed(*coroutines, task_limit=None):
    async def corofn(coro):
        return await coro
    xs = stream.create.raw(coroutines)
    return stream.map.raw(xs, corofn, ordered=False, task_limit=task_limit)
```

But I think it's even better to let map handle the creation of the tasks, so it can be done in a lazy way:
 
```python
xs = stream.iterate(args_gen)
ys = xs | pipe.map(corofn, ordered=True, task_limit=10)
```

I'm closing this issue for now, feel free to re-open it!

**Comment by mdegans** [comment]
Merci! J'ai cherché ça tout la journée. You write some really cool code.
