### ISSUE TITLE
Modifying list of streams during merge iteration

### ISSUE THREAD

**Issue by OllieTerrance** [vxgmichel/aiostream#11]
I'm looking for a way to add or remove asynchronous generators from a stream merge operation during iteration.  Currently I have something like this, which works great:

```python
getters = (transport.receive() for transport in transports)
async with aiostream.stream.merge(*getters).stream() as streamer:                  
    async for msg in streamer:
        process(msg)
```

I'd like to extend this to support both adding new transports and removing existing ones, from outside this loop.  Looking at `base_combine` and `StreamerManager`, it looks like this could be done by exposing the manager and fiddling with `StreamManager.streamers`, though I'm wondering if something like this already exists (the docs suggest not), or if there's perhaps a better way to go about it?

**Comment by vxgmichel** [comment]
Thanks for opening an issue!

First, note that your code can be rewritten as :
```python
await (stream.merge(*getters) | pipe.map(process))
```
> I'd like to extend this to support both adding new transports and removing existing ones, from outside this loop.

It's not clear to me what you mean by outside the loop. Either you want to affect the sub-streamers list at streamer runtime and in this case you could indeed use the `StreamerManager` within a custom operator (which is what `base_combine` is doing). Or, you want different sub-sources for the next run and in this case it'd be simpler to simply craft a new stream.

Or maybe I'm missing something, could you provide more information about your usecase?

**Comment by OllieTerrance** [comment]
> First, note that your code can be rewritten as :
> ```
> await (stream.merge(*getters) | pipe.map(process))
> ```

Oooh, that's nicer.  🙂  Hadn't quite figured out where pipes come in to play...

So, a custom operator sounds like what I might need.  A (hopefully) less contrived example:

```python
class Transport:

    async def start(self):
        # Start queuing things up to be collected from receive().

    async def stop(self):
        # Request to finish up -- retrieve the last batch of messages etc.

    async def receive(self):
        # Implementation varies by subclass, but will always yield messages.
        while True:
            yield Message(...)
```

```python
class Host:

    self.transports = [Transport(...)]

    async def run(self):
        getters = (transport.receive() for transport in self.transports)
        await (aiostream.stream.merge(*getters) | aiostream.pipe.map(self.process))

    async def process(self, msg):
        if ... == "add-transport":  # e.g. from command processing
            transport = Transport(...)
            self.transports.append(transport)
            await transport.start()
            # We've added a new transport, so need to start receiving from it.
        elif ... == "remove-transport":
            transport = ...
            await transport.stop()
            self.transports.remove(transport)
            # Similarly, we need to stop receiving messages from this transport.
```

In reality, the processing is slightly more split up than this (handled by one or more instances of a separate class, managed similarly to transports), but the idea is the same -- the down-the-line processing may change the set of currently-active transports.

`Host.run` is effectively the entry point here (e.g. `loop.run_until_complete(host.run())`), and will run for the lifetime of the process, so I'm currently looking to tap in to the list of streams being merged.

I would expect the remove case to be resolved by making `receive()` return once stopped (which it probably ought to), which reduces the problem to just introducing new streams.  I think recreating the stream is too heavy for this -- it would mean stopping all the transports, clearing the queue (a few messages might still turn up after a stop request), and then restarting them again.

**Comment by vxgmichel** [comment]
I see, interesting! 

One more question, are the `add_transport` and `remove_transport` events only triggered by the content of other `transport.receive()` coroutines, or can they come from other sources as well? If the latter, it probably doesn't make much sense to use a stream operator. I'd go directly for the `StreamManager` (sorry about the poor naming) and use as attribute of `Host`:
```python
    async def run(self, task_limit=None):
        self.manager = StreamerManager(task_limit)
        with self.manager:
            for transport in transports:
                self.manager.enter(transport.receive())
            async for streamer, getter in self.manager.completed():
                try:
                    result = getter()
                except StopAsyncIteration:
                    print('End of transport')
                else:
                    await process(result)
```

**Comment by OllieTerrance** [comment]
I think if I'm going to make this work, it may as well be functional from the outside too.  That seems straightforward enough, I shall give it a go once I'm back in front of a real keyboard.  👍

**Comment by OllieTerrance** [comment]
Seems to do the trick!  I've gained some refactoring tasks by needing a couple of methods to be coroutines, but the hard part of listening to the new receivers is done.  😊

**Comment by OllieTerrance** [comment]
Alright, another puzzle: I'd like to be able to throw an exception into the generator (i.e. `gen.athrow()`) to signal that the generator needs to finish up, without straight up closing it (as that may lose messages still being processed).

As it stands, I've only got the `Streamer` object to work with.  I guess such a method would belong on `AsyncIteratorContext` alonsgside `aclose()` -- calling `streamer._aiterator.athrow(exc)` seems to work as expected, any chance that can be exposed as a public method?

**Comment by vxgmichel** [comment]
> I'd like to be able to throw an exception into the generator (i.e. gen.athrow()) to signal that the generator needs to finish up, without straight up closing it (as that may lose messages still being processed).

The generator already finishes up since `aclose` actually throws a `GeneratorExit` into the generator, meaning the `finally` statements will be executed as expected.

> Any chance that can be exposed as a public method?

Sure, if you think it's worth it.

> I think if I'm going to make this work, it may as well be functional from the outside too.

So did you manage to solve your substream handling issue in a functional way in the end?

**Comment by OllieTerrance** [comment]
> The generator already finishes up since aclose actually throws a GeneratorExit into the generator, meaning the finally statements will be executed as expected.

AIUI `aclose()` is different in that the generator is then unable to return any further values.  My use case is to catch an exception inside the generator, do any cleanup, and return any messages that were still processing (e.g. if interrupted between an API request for messages, and a follow-up request for additional metadata).

> So did you manage to solve your substream handling issue in a functional way in the end?

Well, I may have managed to break things rather substantially (🙄), so I ended up trying to write a minimal solution from scratch.  The result is a class similar to `StreamerManager` that seems to do what I need:

```python
class TransportStream:

    def __init__(self):
        self._coros = {}
        self._transports = {}

    def _queue(self, transport):
        self._transports[ensure_future(self._coros[transport].asend(None))] = transport

    def add(self, *transports):
        for transport in transports:
            self._coros[transport] = transport.receive()
            self._queue(transport)

    async def _wait(self):
        done, _ = await wait(list(self._transports.keys()), return_when="FIRST_COMPLETED")
        for task in done:
            transport = self._transports[task]
            try:
                msg = task.result()
            except StopAsyncIteration:
                del self._coros[transport]
            else:
                # (do something with the message)
                self._queue(transport)
            finally:
                del self._transports[task]

    async def process(self):
        while self._transports:
            try:
                await self._wait()
            except CancelledError:
                for task in self._transports.keys():
                    task.cancel()
                await self._wait()
```

The cleanup handing comes into play when `process()` is cancelled -- the `CancelledError` is propagated to each future wrapping a generator.  Each `receive()` implementation catches it, yields any remaining messages, and terminates.  There's a few downsides to it:

* `agen.asend(None)` is a bit ugly, but that's the best equivalent to `next(gen)` for async I can find.
* If a transport is added whilst `process()` is running, the receive task is queued but won't be read from until one of the other transports yields a message (at which point a new `wait()` is created).

**Comment by vxgmichel** [comment]
> AIUI aclose() is different in that the generator is then unable to return any further values.

Oh yes, I missed this point.

> agen.asend(None) is a bit ugly, but that's the best equivalent to next(gen) for async I can find.

Well, [aiostream.aiter_utils.anext](http://aiostream.readthedocs.io/en/latest/utilities.html#aiostream.aiter_utils.anext) uses `agen.__anext__()`.

> If a transport is added whilst process() is running, the receive task is queued but won't be read from until one of the other transports yields a message (at which point a new wait() is created).

Yes, the fact that `add` can be called outside of `process` makes it quite hard to manage. You'd need a future to set when a transport is added so the `wait` coroutine wakes up and starts monitoring the new transport.

Anyway, it seems like your use case is outside the scope of the `aiostream` operators. Let me know if you find some nice generalization that can be added to the library. Otherwise, I'll close the issue.

**Comment by OllieTerrance** [comment]
Will do, thanks for the insight.  🙂
