### ISSUE TITLE
Ziplast operator

### ISSUE THREAD

**Issue by andersea** [vxgmichel/aiostream#14]
Just thought I'd share some ideas for streams that would be useful to me.

A ziplast stream. It would zip a number of async sequences, but yield a tuple for every item recieved on every stream with each element being the last element recieved on each stream. If no elements have yet been recieved on a stream, the value could be None on the corresponding tuple position. I am really often running into having to coordinate two sequences that yield values at different intervals, one every other second and another every ten seconds, for example.

Merge can kind of achieve this, if you are able tell each element apart, for example by tagging them somehow. If each item has different type, then it is doable, but if each item is a dict for example, then it becomes not so easy to tell where each item came from, unless you wrap it with some metadata.

Also a ratelimit stream. It yields a value at most every n seconds. The rest of the items are discarded.

**Comment by andersea** [comment]
Awesome! That is exactly what I need.

**Comment by vxgmichel** [comment]
Great! I don't really have the time to write the docs and tests for this feature at the moment, so feel free to submit a PR if you're interested. Otherwise, I'll take care of it later.

**Comment by andersea** [comment]
Np, thanks for the effort. I really like this library and async generator functions is a pretty nice new python feature. It really cleans up a lot of my previous async context manager code in the project I am currently working at. You get a feeling that async/await is still a pretty young feature in python and there are definitely a few pitfalls to dodge here and there.

**Comment by vxgmichel** [comment]
Hi @andersea,

I just added the `ziplatest` operator (see PR #22), it will become available with version 0.3.1.

Thanks for the suggestion :)
