### ISSUE TITLE
merge example

### ISSUE THREAD

**Issue by mlmarius** [vxgmichel/aiostream#16]
Could you please demonstrate an example of using the merge function ?

**Comment by vxgmichel** [comment]
Hi @mlmarius,

Here's a simple example that could be added to the docs if you find it useful:

```python
import random
import asyncio
from aiostream import stream, pipe


async def agen(gid):
    while True:
        x = random.random()
        await asyncio.sleep(x)
        yield gid, x


async def main():
    agens = map(agen, range(10))
    xs = stream.merge(*agens) | pipe.print()
    await xs


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

A possible output:

```
(8, 0.5857707944753592)
(6, 0.6053961377023365)
(2, 0.6245681280757353)
(1, 0.6307368570696441)
(9, 0.6466763748758125)
(8, 0.08248583822040778)
(8, 0.02950240705570728)
(8, 0.00360015657691537)
[...]
```

**Comment by mlmarius** [comment]
Thanks for the reply @vxgmichel . I was trying to do it like so:

```
      async def get(self):
          url1 = 'url1'
          url2 = 'url2'
          gens = [downloader.fetch(url1), downloader.fetch(url1)]
          async for batch in stream.merge(*gens):
              self.write(batch)
              await self.flush()
```
I think it works but I keep getting this warning: " UserWarning: AsyncIteratorContext is iterated outside of its context
  "AsyncIteratorContext is iterated outside of its context")". What am I not doing properly?

**Comment by mlmarius** [comment]
I think this is how to properly open the context:

      async def get(self):
          url1 = 'url1'
          url2 = 'url2'
          gens = [downloader.fetch(url1), downloader.fetch(url1)]
          async with stream.merge(*gens).stream() as chunks:
              async for chunk in chunks:
                  self.write(batch)
                  await self.flush()

**Comment by vxgmichel** [comment]
@mlmarius 
> I think this is how to properly open the context:
> [...]
>   `async with stream.merge(*gens).stream() as chunks:`

Exactly, this guarantees that any resource held by the `downloader.fetch` coroutines will be cleaned up when exiting the asynchronous context. The same guarantee applies for my previous example, since the safe context is used automatically when awaiting a stream. Using your example:

```python
async def self.write_and_flush(self, batch):
    self.write(batch)
    await self.flush()

async def get(self):
    agens = map(downloader.fetch, self.urls)
    xs = stream.merge(*agens) | pipe.map(self.write_and_flush)
    await xs
```
