### ISSUE TITLE
Appending to merged during iteration

### ISSUE THREAD

**Issue by jamesstidard** [vxgmichel/aiostream#18]
Sorry if I've missed this looking through the documentation. But I was wondering if it's possible to append to a `aiostream.stream.merge` during iteration (or some other equivalent logic).

Here's some pseudo-ish code of the logic I'd like to be able to achieve:

```python
from asyncio import sleep, run
from aiostream.stream import merge

async def go():
    yield 0
    await sleep(1)
    yield 50
    await sleep(1)
    yield 100

async def main():
    tasks = merge(go(), go(), go())

    async for v in tasks:
        if v == 50:
            tasks.merge(go())
        print(v)

if __name__ == '__main__':
    run(main())
```

i.e. the `async for v in tasks` should never complete but continue to add new generators into the stream. Hope that makes some sense.

Thanks for the work on these tools, by the way.

**Comment by vxgmichel** [comment]
Hi @jamesstidard, thanks for creating this issue.

There's been a similar discussion on this issue tracker: #11.

The advanced operators (such as `concat`, `flatten` and `switch`) need the kind of logic you describe because they all deal with asynchronous sequence of sequences. So I abstracted the logic of adding and removing streamers on the fly in an asynchronous context manager called [StreamerManager](https://github.com/vxgmichel/aiostream/blob/64225e2a6bb665b5fe382eb892d8b827efb9248e/aiostream/manager.py#L13).

In your example, it would look like this:
```python
async with StreamerManager() as manager:
    for task in [go(), go(), go()]:
        await manager.enter(task)
    async for streamer, getter in manager.completed():
        try:
            result = getter()
        except StopAsyncIteration:
            pass
        else:
            if result == 50:
                await manager.enter(go())
            print(result)
            manager.schedule(streamer)
```

However, the reason why this helper is not exposed (nor documented) is because it doesn't fit the philosophy behind aiostream (i.e, building pipelines of functional operators). So feel free to use it but keep it mind that it might be changed or removed in the future.

Note that it's also possible to implement the pattern in your example using aiostream operators and an asyncio queue as feedback channel:

```python
queue = asyncio.Queue()
await queue.put(go())
await queue.put(go())
await queue.put(go())

await (stream.repeat(())
       | pipe.starmap(queue.get)
       | pipe.flatten()
       | pipe.print()
       | pipe.filter(lambda x: x == 50)
       | pipe.map(lambda _: go())
       | pipe.map(queue.put))
```

**Comment by jamesstidard** [comment]
Oh thanks @vxgmichel , sorry for not spotting you have already had an issue like mine opened before.

Those suggestions look great. I'd lean towards the second one but just need to spend some time getting my head around the syntax a little. I've done a little Rx stuff before but I'm not fluent.

Thanks again.

**Comment by vxgmichel** [comment]
> sorry for not spotting you have already had an issue like mine opened before.

No problem ;)

> I'd lean towards the second one but just need to spend some time getting my head around the syntax a little.

I just edited my previous comment to fix the pipeline and add the imperative equivalent, this should help a bit.

**Comment by jamesstidard** [comment]
I ended up actually using the StreamingManager instead because I wanted to be able to handle exceptions.

Could I take advantage of your goodwill a little more and just double check I'm using this in the correct way. Like the example I gave above but I want to be able to track a response back to what initiated it. I'm currently using the `streamer` as a key. So I'm assuming that that a streamer is created per task entered into the manager and that same streamer is returned when values are yielded from that task.

for example:

```python
import random

from asyncio import sleep, run
from aiostream.manager import StreamerManager



async def go(error=False):
    yield 0
    await sleep(1)
    yield 50
    if error:
        raise RuntimeError()
    await sleep(1)
    yield 100


async def main():
    async with StreamerManager() as manager:
        parents = {}

        for task in [go(), go(), go()]:
            task_streamer = await manager.enter(task)
            parents[task_streamer] = task

        async for streamer, getter in manager.completed():
            try:
                result = getter()
            except StopAsyncIteration:
                print('complete')
                del parents[streamer]
            except RuntimeError:
                print('dead')
            else:
                if result == 50:
                    error = random.choice([True, False])
                    new_task = go(error=error)
                    task_streamer = await manager.enter(new_task)
                    parents[task_streamer] = new_task
                print(result, 'called by', parents[streamer])
                manager.schedule(streamer)


if __name__ == '__main__':
    run(main())
```

From my testing it appears to work but just want to double check.

Thanks again.

**Comment by vxgmichel** [comment]
> So I'm assuming that that a streamer is created per task entered into the manager and that same streamer is returned when values are yielded from that task.

Correct. You can compare with the implementation of [stream.advanced.base_combine](
https://github.com/vxgmichel/aiostream/blob/64225e2a6bb665b5fe382eb892d8b827efb9248e/aiostream/stream/advanced.py#L16), it does something very similar.

> I ended up actually using the StreamingManager instead because I wanted to be able to handle exceptions.

It's true that `stream.flatten`  and the other advanced operators don't provide any exception handling. For instance, `asyncio.gather` has a `return_exceptions=False` optional argument. Maybe we should implement something similar.

**Comment by vxgmichel** [comment]
> I'll stick with those manager.schedule calls in all but the StopIteration as that seems to be behaving correctly.

I don't think it makes sense to schedule a faulty streamer. The reason why it works is because awaiting `__anext__` on an asynchronous generator that has previously raised an exception causes a `StopAsyncIteration`, but it seems like an implementation detail. 

Basically, I would treat exceptions this way:
- `StopAsyncIteration` is raised: the generator has terminated without error.
- another exception is raised: the generator has terminated with an error.

> Thanks again for the library, seems great. I also just realised I've used your other aioconsole lib in the past as well. Also a great experience.

Cool, you're welcome :)

**Comment by jamesstidard** [comment]
Oh OK, so you should only schedule streamers when they have returned without error? So just the `else` statement. And looking at the implementation of .enter it appears to call `.schedule` for you so no need to schedule after adding a new async generator. 👍

**Comment by vxgmichel** [comment]
> so you should only schedule streamers when they have returned without error?

Yes, because a faulty generator it's not going to produce any more items anyway.

> And looking at the implementation of `.enter` it appears to call `.schedule` for you so no need to schedule after adding a new async generator.

Yes but it seems you already took that into account in the [example](https://github.com/vxgmichel/aiostream/issues/18#issuecomment-406015411) you gave earlier.
