### ISSUE TITLE
aislice aenumerate?

### ISSUE THREAD

**Issue by AlJohri** [vxgmichel/aiostream#2]
would it be possible to add `aislice` and `aenumerate` functions that match the interface of the synchronous versions? https://stackoverflow.com/questions/42378566/python-3-6-async-version-of-islice

while I definitely want to look into doing stream processing things with asyncio + aiostream, I have usecases where I just need to mimic the synchronous interface and its easier to use the API I'm already familiar with. thanks!

example usecase:

```python
def test_sync():
    gen = craigslist.search('washingtondc', 'apa', postal=20071, search_distance=1)
    for post in islice(gen, 0, 110):
        pass

@pytest.mark.asyncio(forbid_global_loop=False)
async def test_async():
    gen = craigslist.search_async('washingtondc', 'apa', postal=20071, search_distance=1)
    async for post in aislice(gen, 0, 110):
        pass
```

**Comment by vxgmichel** [comment]
Thank you for the report, does the following code fit your use case?

```python
from aiostream import stream
aenumerate = stream.enumerate 
aislice = stream.select.slice
```
