### ISSUE TITLE
buffer/batch streams

### ISSUE THREAD

**Issue by sagarr** [vxgmichel/aiostream#37]
Hi, I want to create a batch/buffer of streams, something like [Buffer from reactive](http://reactivex.io/documentation/operators/buffer.html).
    
    xs = stream.count(interval=0.2)

    # Operators can be piped using '|'
    ys = xs | pipe.batch(2)

    # Use a stream context for proper resource management
    async with zs.stream() as streamer:

        # Asynchronous iteration
        async for z in streamer:
            # Print (0,1) , (2,3), ... 
            print('->', z)`

**Comment by vxgmichel** [comment]
Hi @sagarr, what about [stream.chunks](https://aiostream.readthedocs.io/en/stable/operators.html#aiostream.stream.chunks)?

```python
xs = stream.count(interval=1)
ys = xs | pipe.chunks(2)
await (ys | pipe.print())
```
It prints:
```
[0, 1]
[2, 3]
[...]
```

**Comment by sagarr** [comment]
How could I miss that, solved, thanks :+1:
