### ISSUE TITLE
How to close the async stream in the middle of execution.

### ISSUE THREAD

**Issue by rvpanchani** [vxgmichel/aiostream#38]
I am creating a several pipelines using aiostream and wanted to stop any specific running pipeline on external event. What could be the cleaner approach to stop the already running pipeline. I cannot close or stop the event loop because the same event loop is shared by all the pipeline tasks.

**Comment by vxgmichel** [comment]
Hi @rvpanchani,

Cancelling and awaiting the task corresponding to a specific pipeline should be enough to ensure a clean stop. Please let me know if that helps :)

**Comment by rvpanchani** [comment]
@vxgmichel  - It worked i forgot to reply due to lost in solving other issues :) Thanks Michel
