### ISSUE TITLE
groupby operator

### ISSUE THREAD

**Issue by piyush-jaiswal** [vxgmichel/aiostream#39]
Hi,
Great library. I had a use-case where the ```groupby``` operator from ```itertools``` would come in handy, but I can't find a similar operator here. Is there a way to achieve similar functionality using the existing operators?

**Comment by vxgmichel** [comment]
Thanks @piyush-jaiswal :)

There's been a [discussion](https://github.com/vxgmichel/aiostream/pull/31) about this operator. I ended up writing a groupby operator (see this [gist](https://gist.github.com/vxgmichel/ad2aef82dd849d346dc20c3127af026c)). It never made it into the library though, maybe we should reconsider it.
