### ISSUE TITLE
Waiting for 0.3.2 release

### ISSUE THREAD

**Issue by and-semakin** [vxgmichel/aiostream#41]
Seems like some good stuff was merged after 0.3.1 release, i.e. fixed annoying `DeprecationWarning` issue. When 0.3.2 will be released?

**Comment by vxgmichel** [comment]
Wow, almost a year since the last release!
Here you go: [v0.3.2](https://github.com/vxgmichel/aiostream/releases/tag/v0.3.2) :)

**Comment by and-semakin** [comment]
Wow! Thank you for quick answer!
