### ISSUE TITLE
Pipeable Operator Gives No Explanation of Issue

### ISSUE THREAD

**Issue by t-mart** [vxgmichel/aiostream#49]
Hello! I'm new to aiostream (but am already very impressed and excited to use it).

I'm trying to convert my code from the `async with ... async for` syntax to the more concise `pipe` syntax.

The code I'm writing this for is a development web server that [watches a few directories for filesystem changes (modify, add, delete)](https://github.com/samuelcolvin/watchgod) and then, will regenerate the site when a change occurs.

The whole reason I'm using aiostream is because my interface to watch the directories is _asynchronous_, but does not support watching _multiple_ paths. Therefore, I need to combine (`merge` in aiostream parlance?) a **list** of watchers and iterate over their change events.

Change events from the watchers can obviously happen at any time. Also, the watchers will watch the directories indefinitely (I've been reading around about properly closing the StreamContext on completion, but as of now, the only way out for this code is a Ctrl-C from the user).

Here's an excerpt of what I'm doing. The working `async with ... async for` is in the `watch` method, commented:

```python
async def watch(app: web.Application) -> None:
    app.logger.info(f"Watching {', '.join(map(str, app["generator"].watch_paths))} for changes")

    # THIS is the code that works! Minus the @operator decoration on regenerate
    # async with stream.merge(*[awatch(p) for p in watch_paths]).stream() as s:
    #     async for changedset in s:
    #         await regenerate(changedset, app)

    # This is the code that I'm trying to get work, but am getting no feedback as to the problem
    await (stream.merge(*[awatch(p) for p in watch_paths]) | regenerate(app))

@core.operator(pipable=True)
async def regenerate(changedset: Set[Tuple[Change, str]], app: web.Application) -> None:
    changed_files = ", ".join(path for change_type, path in changedset)
    app.logger.info(
        f"Regenerating site because the following files have changed: {changed_files}"
    )
    generated = await generate(app, False)
```

In the above implementation, `regenerate` is never entered for some reason and aiostream library is giving me no indication as to why. This is at least bug on my part, but optimistically, an example of where logging may be improved. Thank you!

**Comment by vxgmichel** [comment]
Hi @t-mart, thanks for your report :)

I tried to reproduce your problem, and I did get a proper exception out of it. For instance, consider the following code:
```python
import asyncio
from aiostream import operator


@operator(pipable=True)
async def some_pipable_operator(source, arg):
    await asyncio.sleep(1)


async def main():
    some_pipable_operator("test")

if __name__ == "__main__":
    asyncio.run(main())
```
Just like in your snippet, `regenerate` is incorrectly instantiated:
- the first argument is not an async iterable
- the second argument is missing

In this case it's the first error that is reported first:
```python-tb
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    asyncio.run(main())
  File "/home/vinmic/miniconda/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/vinmic/miniconda/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 12, in main
    some_pipable_operator("test")
  File "/home/vinmic/aiostream/aiostream/core.py", line 284, in init
    assert_async_iterable(args[0])
  File "/home/vinmic/aiostream/aiostream/aiter_utils.py", line 61, in assert_async_iterable
    f"{type(obj).__name__!r} object is not async iterable")
TypeError: 'str' object is not async iterable
```

For your information, the proper usage of user-defined pipable operator is:
```python

import asyncio
from aiostream import stream, operator


@operator(pipable=True)
async def some_pipable_operator(source, arg):
    assert await source == "a"
    yield arg


async def main():
    result = await (stream.just("a") | some_pipable_operator.pipe("b"))
    assert result == "b"

if __name__ == "__main__":
    asyncio.run(main())
```

However, it seems to me that you don't need a user-defined pipable operator. Instead, simply use [stream.map](https://aiostream.readthedocs.io/en/latest/operators.html#aiostream.stream.map):

```python
from functools import partial
from aiostream import stream, pipe

async def watch(app: web.Application) -> None:
    func = functool.partial(regenerate, app=app)
    await (stream.merge(*[awatch(p) for p in watch_paths]) | pipe.map(func))

async def _regenerate(changedset: Set[Tuple[Change, str]], app: web.Application) -> None:
    [...]
```

Hope that helps :)

**Comment by t-mart** [comment]
Fantastic. Thank you for your help.

I wasn't getting the exception because, while I did `create_task` all this code, I wasn't awaiting it. (It's amazing it was running at all. Maybe aiohttp `application.on_startup` was helping me in some way I don't understand.) For many Python programmers, thinking asynchronously will take some getting-used-to.

Sorry to stuff up your issues with a non-issue. I'd definitely be in favor of a help channel of some kind, whether that be gitter or IRC or discord etc.
