### ISSUE TITLE
Add a concurrent queue runner

### ISSUE THREAD

**Issue by orf** [vxgmichel/aiostream#5]
#Hey,
Thanks for this awesome library! I was wondering if it would be a good idea to add a `concurrent()` method to operators?

i.e:

```python
urls = ['google.com', 'reddit.com', 'github.com']

@operator(pipable=True)
def fetch(source):
    async with streamcontext(source) as streamer:
        async for i, item in streamer:
             yield fetch_url(item)

stream = iterate(urls) | fetch().concurrent(2) | parse()
```

This stream would cause the `fetch` operator to run two concurrent tasks, allowing two concurrent HTTP requests to be made (through the imaginary `fetch_url` method). Of course this would cause any downstream operators to receive items out of order, but in some cases this is OK.

**Comment by vxgmichel** [comment]
Thank you for your report!

I think this is closely related to issue #1, since you could write:

```python
coros = map(fetch_url, urls)
xs = stream.as_completed(coros)
```
(given the `as_completed` operator is implemented). 

Using issue #2, it could also be written as:

```python
async def fetch(url):
    yield await fetch_url(url)

stream.iterate(urls) | pipe.flatmap(fetch, limit=2)
``` 
(given the operator `flatmap` is implemented).

**Comment by orf** [comment]
Ahh yeah, #3 is the better choice I think. It's a tad verbose but it does the job :+1:

I'll close this
