### ISSUE TITLE
Preserve an aiohttp streaming response.

### ISSUE THREAD

**Issue by tiptop96** [vxgmichel/aiostream#68]
I am looking to preserve an `aiohttp` streaming response through their [async iterator](https://docs.aiohttp.org/en/stable/streams.html#asynchronous-iteration-support).

The idea is to stream a response to check for a specific criteria that will appear somewhere in the first 5-20 lines of the response and if it is not matched we would close the stream, and if it is matched we would pipe it into a blob storage service.

However I cannot seem to preserve the stream. I have tried this a few way but I cannot seem to get it right.

At first I figured that this it would be something as simple as this:
```python
async def main():
    async with aiohttp.ClientSession() as sesh:
        async with sesh.get("https://jsonplaceholder.typicode.com/todos/1") as resp:
            async with stream.preserve(resp.content).stream() as streamer:
                # This loop runs
                async for line in streamer:
                    print(line)
                    await asyncio.sleep(1)
            # This loop doesn't
            async for line in resp.content:
                print(line)
                await asyncio.sleep(1)   
```
As the comments say, only one loop runs.

I also tride wrapping the stream in an `aiostream.stream.operator` but it gave me an exception:
```python
content = operator(resp.content)
```
```
Traceback (most recent call last):
  File "test_preserve_http.py", line 29, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "test_preserve_http.py", line 10, in main
    content = operator(resp.content)
  File "/Users/tiptop96/concepts/.env/lib/python3.6/site-packages/aiostream/core.py", line 368, in operator
    return decorator if func is None else decorator(func)
  File "/Users/tiptop96/concepts/.env/lib/python3.6/site-packages/aiostream/core.py", line 273, in decorator
    name = func.__name__
```
As a side note, I also receive a warning as follows:
![bild](https://user-images.githubusercontent.com/31468763/110305493-0870dd80-7ffd-11eb-9ba5-e5cec26d5e78.png)
If I remove the `stream()` call it also raises an exception.

Any guidance on how to do this or if it is even possible is much appreciated. 👍

**Comment by tiptop96** [comment]
Ahh my bad for missunderstanding the operator! But this is awesome, thanks so much for the thorough response and the awesome lib! 🔥

**Comment by vxgmichel** [comment]
No problem :)
