### ISSUE TITLE
Cancelling during `merge` iteration emits waring

### ISSUE THREAD

**Issue by SillyFreak** [vxgmichel/aiostream#7]
Consider this code:

```python
async def main():
    async def values(value):
        while True:
            await asyncio.sleep(0.2)
            yield value

    async def task():
        async for value in merge.raw(values("a")):
            print(value)

    try:
        await asyncio.wait_for(task(), 0.5)
    except asyncio.TimeoutError:
        pass

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

I get the following output:

    a
    a
    Task was destroyed but it is pending!
    task: <Task pending coro=<async_generator_asend()> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2324a9f168>()]> cb=[_wait.<locals>._on_completion() at /usr/lib64/python3.6/asyncio/tasks.py:380]>

this can be fixed by adding a `try`/`except` in [merge](https://github.com/vxgmichel/aiostream/blob/master/aiostream/stream/combine.py#L80):

    streamers = {}
    try:
        # ...
    except asyncio.CancelledError:
        for task in streamers:
            task.cancel()
        raise

It probably happens at other places where `asyncio.ensure_future` is used, I'll have a look.

**Comment by SillyFreak** [comment]
Thanks for the quick action! One thing I noticed is, commenting out the line

    stack.callback(cleanup)

lets the warnings return, but does not break the test. Just if you didn't notice it - I wouldn't know how to fix that...

**Comment by vxgmichel** [comment]
Thanks for testing the PR!

Yea I noticed that. I think it's related to `asyncio.test_utils.TestLoop` not issuing proper warnings on `loop.close`, but I'm postponing this investigation for now :sweat_smile: 

I'm merging the PR, let me know if you need a release right away.

**Comment by SillyFreak** [comment]
Right now I'm mostly experimenting, so it's fine. Maybe something else comes up and I can report it due for the same release. ;) Thanks for the library, by the way. Reading it has already taught me some cool thinks on asyncio!
