### ISSUE TITLE
Please upload a wheel release to pypi

### ISSUE THREAD

**Issue by gilbahat** [vxgmichel/aiostream#81]
Hi,

Please upload a wheel distribution to pypi. this makes for faster package installations. I'm not a package maintainer myself and thus can't test it but this may be a matter of simply adding 'bdist_wheel' after 'sdist' in the appropriate github action.

**Comment by vxgmichel** [comment]
Hi @gilbahat, thank you for the report

> Please upload a wheel distribution to pypi

[Done](https://files.pythonhosted.org/packages/4a/29/d94dc724b543d0ff16e177a3ce4eaa6253afb6350aa7ba372a8fe7e01f20/aiostream-0.4.5-py3-none-any.whl) :tada:

**Comment by gilbahat** [comment]
Thank you so much!
