### ISSUE TITLE
Regarding `update_pipe_module`

### ISSUE THREAD

**Issue by andrewshvv** [vxgmichel/aiostream#87]
Just wanted to point out, that while this is a very cool trick, it isn't picked up by an IDE like Pycharm for example.
https://github.com/vxgmichel/aiostream/blob/main/aiostream/pipe.py#L9

This leads to the `Cannot find reference 'filter' in 'pipe.py` syntax warning highlights.

Maybe there is an alternative?

**Comment by vxgmichel** [comment]
Hi @andrewshvv and thanks for the report!

This should be fixed with PR #88 :)

**Comment by vxgmichel** [comment]
The fix is out, see [v0.5.2](https://github.com/vxgmichel/aiostream/releases/tag/v0.5.2) :tada:

**Comment by andrewshvv** [comment]
Thank you very much!
