### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by jhamman** [vxgmichel/aiostream#94]
@vxgmichel - very cool project! Thanks for creating it. I recently went round and round on a problem before finding aiostream and this absolutely solve my problem 🙌 .

Question for you: could you be convinced to change the license of aiostream to something more friendly (e.g. MIT or Apache 2)? I'd love to consider using this project in an OSS project of ours but we can't take on a GPL dependency. Thanks for considering!

**Comment by vxgmichel** [comment]
Hi @jhamman, I'm glad that you found this project useful :)

I'd like to stick with GPL as I'm quite keen on making sure that my personal projects are not going to be used in proprietary software. It's unfortunate that some OSS project like yours are not able to use it tho, I wish there was some middle ground.

**Comment by jhamman** [comment]
@vxgmichel - thanks for the quick response. It sounds like you have a pretty firm position on this so I won't try too hard to push you off that mark. If you open to a change, I'd be happy to help in any way necessary to help move things along.

The one thing I will say is that I come from the open source Scientific Python community (NumPy, SciPy, etc.), where this has been discussed at length, more permissive licenses are the norm (BSD, Apache, and MIT being the most popular). Yes, this often means that these get used by commercial and I believe this is seen as an net-good thing. 

Lastly, you might be interested to know that the library I was considering using aiostream is [Zarr-Python](https://github.com/zarr-developers/zarr-python) -- where we're building a new async/streaming interface for accessing multi-dimensional arrays and metadata.

**Comment by vxgmichel** [comment]
Solved by mail after sharing [this gist](https://gist.github.com/vxgmichel/23469ee482aeba4a1c4d3cd66f1ac6c5) with [MIT licensing](https://gist.github.com/vxgmichel/13bb00666430ab8dcc47d1f7dd148579) :)
